QCamera2Factory: Ifdef unused parameter hw_device
error: unused parameter 'hw_device' [-Werror,-Wunused-parameter]
        int32_t cameraId, uint32_t halVersion, struct hw_device_t** hw_device)
                                                                    ^

Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>